### PR TITLE
[SER-379] Create demo project in Unity 2021

### PR DESCRIPTION
**Pull request by tomthecarrot**

### CODE REVIEW

**Review by TheButlah — APPROVED** [review]
I see the test scene as an empty scene. Approving since I assume that is correct?

**Review by TheButlah — CHANGES_REQUESTED** [review]
Actually, lets put this in `demos/unity_states/unity`

this will let us put the rust code specific to the demo under `demos/unity_states/rust`

**Comment by tomthecarrot** [comment]
> Actually, lets put this in `demos/unity_states/unity`
> 
> this will let us put the rust code specific to the demo under `demos/unity_states/rust`

Good idea, updated.

**Comment by TheButlah** [comment]
Do we still need the `PlatformTest` directory? Seems redundant

**Comment by tomthecarrot** [comment]
> Do we still need the `PlatformTest` directory? Seems redundant

This was to keep the project name descriptive in the Unity Editor's title bar, since I often have 2 or 3 Unity Editors up for different purposes across Movieoke and Platform. You're right though, it is redundant. Moving.

**Review by TheButlah — APPROVED** [review]

**Comment by TheButlah** [comment]
Whatever you think works best, if we need to make it a redundant folder for the sake of readability, thats fine

**Pull request merged**
